// Generated by GG/scripts/sync-game-menus.mjs.
export const GAME_MENU = {
  "selector": "[data-gg-pregame]",
  "steps": {
    "en": [
      "Buy properties, collect rent and be the last player with money.",
      "Roll the dice on your turn, then choose Buy or decline. Use the property controls to build and trade.",
      "Complete a color set before building houses. Keep cash for rent and taxes."
    ],
    "ru": [
      "Покупай улицы, собирай ренту и останься последним игроком с деньгами.",
      "В свой ход бросай кубики, покупай участки или отказывайся. Управляй стройкой и сделками через карточки улиц.",
      "Собери цветовую группу перед строительством и оставляй деньги на ренту и налоги."
    ]
  }
}
