// English translations keyed by the exact Russian source string.
// Russian stays the default; t(ru) returns EN[ru] when the language is English.
export const EN: Record<string, string> = {
  // -- Brand / app ----------------------------------------------------------
  'Магнат': 'Magnate',
  'МАГНАТ': 'MAGNATE',
  'Раскладываем поле…': 'Setting up the board…',

  // -- Board tile names (property streets) ----------------------------------
  'Заречная': 'Riverside',
  'Полевая': 'Meadow St.',
  'Садовая': 'Garden St.',
  'Лесная': 'Forest St.',
  'Гагарина': 'Gagarin Ave.',
  'Пушкина': 'Pushkin St.',
  'Арбат': 'Arbat',
  'Тверская': 'Tverskaya',
  'Невский': 'Nevsky Ave.',
  'Дерибасовская': 'Deribasivska',
  'Рублёвка': 'Rublyovka',
  'Остоженка': 'Ostozhenka',
  // stations & utilities
  'Южный вокзал': 'South Station',
  'Западный вокзал': 'West Station',
  'Северный вокзал': 'North Station',
  'Восточный вокзал': 'East Station',
  'Электростанция': 'Power Plant',
  'Водоканал': 'Water Works',
  // special tiles
  'Старт': 'Start',
  'Казна': 'Treasury',
  'Подоходный налог': 'Income Tax',
  'Тюрьма': 'Jail',
  'Шанс': 'Chance',
  'Отдых': 'Free Rest',
  'На нары': 'Go to Jail',
  'Налог на роскошь': 'Luxury Tax',

  // -- Board tile short labels (drawn on the board) -------------------------
  'СТАРТ': 'START',
  'Ю. вокзал': 'S. Station',
  'З. вокзал': 'W. Station',
  'С. вокзал': 'N. Station',
  'В. вокзал': 'E. Station',
  'Электро': 'Power',
  'Водокан.': 'Water',
  'Дерибас.': 'Deribas.',
  'Остожен.': 'Ostozh.',
  'Налог': 'Tax',
  'Роскошь': 'Luxury',
  'залог': 'mortgaged',

  // -- Colour group labels --------------------------------------------------
  'Окраина': 'Outskirts',
  'Тихий центр': 'Quiet Centre',
  'Проспекты': 'Avenues',
  'Бульвары': 'Boulevards',
  'Набережные': 'Waterfronts',
  'Элитка': 'Uptown',
  'Вокзалы': 'Stations',
  'Предприятия': 'Utilities',

  // -- Chance cards ---------------------------------------------------------
  'Беспроигрышная лотерея! Банк выплачивает 2000.': 'A sure-win lottery! The bank pays you 2000.',
  'Проезд до Старта. Получите зарплату.': 'Advance to Start. Collect your salary.',
  'Штраф за превышение скорости: 400.': 'Speeding fine: 400.',
  'Вас переводят на Невский проспект.': 'You are sent to Nevsky Ave.',
  'Отойдите на 3 клетки назад.': 'Move back 3 spaces.',
  'Полиция задержала вас. Отправляйтесь на нары.': 'The police caught you. Go to Jail.',
  'Освобождение из тюрьмы без залога. Сохраните карту.': 'Get out of jail free. Keep this card.',
  'Дивиденды по акциям: 1000.': 'Stock dividends: 1000.',

  // -- Chest cards ----------------------------------------------------------
  'Возврат налогов. Банк выплачивает 1500.': 'Tax refund. The bank pays you 1500.',
  'День рождения! Каждый игрок дарит вам 300.': 'Happy birthday! Each player gives you 300.',
  'Оплата счёта за лечение: 600.': 'Pay your medical bill: 600.',
  'Наследство. Банк выплачивает 2000.': 'Inheritance. The bank pays you 2000.',
  'Вы устроили вечеринку. Заплатите каждому по 250.': 'You threw a party. Pay each player 250.',
  'Штраф за парковку: 300.': 'Parking fine: 300.',

  // -- App.tsx: difficulty picker ------------------------------------------
  'Легко': 'Easy',
  'Спокойная партия': 'A relaxed game',
  'Средне': 'Medium',
  'Достойные соперники': 'Worthy opponents',
  'Сложно': 'Hard',
  'Безжалостные магнаты': 'Ruthless magnates',
  'Выбери сложность': 'Choose difficulty',
  'Понятно': 'Got it',

  // -- App.tsx: result modal -----------------------------------------------
  'Ты магнат!': 'You are a magnate!',
  'Победил': 'Winner:',
  'монет': 'coins',
  'Ты разорил соперников и остался на вершине.': 'You bankrupted your rivals and stayed on top.',
  'В следующий раз повезёт больше!': 'Better luck next time!',
  'В меню': 'To menu',
  'Играть ещё 🎲': 'Play again 🎲',
  'Домой': 'Home',

  // -- store.ts: toasts & flashes ------------------------------------------
  'Тебя отправили на нары': 'You were sent to jail',
  'обанкротился': 'went bankrupt',
  'Не получилось, попробуй ещё': 'That did not work, try again',
  'Не удалось создать комнату. Проверь связь.': 'Could not create a room. Check your connection.',
  'Не удалось подобрать игру. Проверь связь.': 'Could not find a match. Check your connection.',
  'Нет комнаты с таким кодом.': 'No room with that code.',
  'Игра уже началась.': 'The game has already started.',
  'В комнате нет мест.': 'The room is full.',
  'Не удалось войти.': 'Could not join.',
  'Не удалось начать': 'Could not start',

  // -- Home.tsx -------------------------------------------------------------
  'Скупай улицы, собирай монополии, разоряй соперников': 'Buy up streets, build monopolies, bankrupt your rivals',
  'Победы': 'Wins',
  'Серия': 'Streak',
  'Монеты': 'Coins',
  'Одиночная игра': 'Single player',
  'Против ботов, выбери сложность': 'Against bots - pick a difficulty',
  'Быстрая игра': 'Quick match',
  'Случайные соперники онлайн': 'Random opponents online',
  'Игра с друзьями': 'Play with friends',
  'Создай комнату и поделись кодом': 'Create a room and share the code',
  'Войти по коду': 'Join by code',
  'Введи код из 4 символов': 'Enter a 4-character code',
  'Рейтинг': 'Leaderboard',
  'Правила': 'Rules',

  // -- Board.tsx ------------------------------------------------------------
  'Выйти': 'Leave',
  'РАУНД': 'ROUND',
  'Ходит': 'Turn:',
  'ходит…': 'is playing…',
  'Залог': 'Bail',
  'Купить за': 'Buy for',
  'Платишь налог': 'Pay tax of',
  'в банк.': 'to the bank.',
  'бросок': 'roll',
  'сейчас': 'now',
  'дом': 'house',
  'дома': 'houses',
  '1 вокзал': '1 station',
  '2 вокзала': '2 stations',
  '3 вокзала': '3 stations',
  '4 вокзала': '4 stations',
  '✦ Твой ход': '✦ Your turn',
  'Ты': 'You',
  'банкрот': 'bankrupt',
  'Партия окончена': 'Game over',
  'Ты в тюрьме': 'You are in jail',
  'Твой ход': 'Your turn',
  'Выйти по карте': 'Use jail card',
  'Бросок на дубль 🎲': 'Roll for doubles 🎲',
  'Бросить кубики 🎲': 'Roll the dice 🎲',
  'Строить 🏠': 'Build 🏠',
  'Твой капитал': 'Your cash',
  'Капитал': 'Cash',
  'Ждём ход соперника…': 'Waiting for your opponent…',
  'Заплати залог или попробуй выбросить дубль': 'Pay the fine or try to roll doubles',
  'Купишь недвижимость?': 'Buy this property?',
  'Можно бросить кубики или построить дом': 'Roll the dice or build a house',
  'Бросай кубики и ходи по кругу': 'Roll the dice and move around the board',
  // rent table
  'Аренда': 'Rent',
  'Монополия (без домов)': 'Monopoly (no houses)',
  '1 дом': '1 house',
  '2 дома': '2 houses',
  '3 дома': '3 houses',
  '4 дома': '4 houses',
  'Отель': 'Hotel',
  '1 предприятие': '1 utility',
  '2 предприятия': '2 utilities',
  // special descriptions
  'Проходя мимо, получаешь зарплату 2000 ₽.': 'Pass by to collect a 2000 ₽ salary.',
  'Просто стоишь в гостях, если не попал за решётку.': 'Just visiting, unless you were locked up.',
  'Спокойная клетка. Ничего не происходит, можно выдохнуть.': 'A calm space. Nothing happens - take a breather.',
  'Отправляешься прямиком на нары.': 'You go straight to jail.',
  'Тянешь карту «Шанс»: движение, штраф или удача.': 'Draw a Chance card: movement, a fine, or luck.',
  'Тянешь карту «Казна»: чаще про деньги.': 'Draw a Treasury card: usually about money.',
  // info sheet
  'Цена': 'Price',
  'Владелец:': 'Owner:',
  'ты': 'you',
  'Дом:': 'House:',
  'строить можно на полной группе': 'buildable on a full group',
  'в залоге': 'mortgaged',
  'Пока ничей': 'Unowned',
  'Закрыть': 'Close',
  // buy sheet
  'Свободная недвижимость': 'Property for sale',
  'Не хватает денег': 'Not enough money',
  'Пропустить': 'Skip',
  // build sheet
  'Построить дом 🏠': 'Build a house 🏠',
  'Дома поднимают аренду. Пятый дом это отель.': 'Houses raise the rent. The fifth house is a hotel.',
  'Пока строить негде.': 'Nowhere to build yet.',
  'станет отелем': 'becomes a hotel',

  // -- Lobby.tsx ------------------------------------------------------------
  'КОД': 'CODE',
  'Входим…': 'Joining…',
  'Войти в игру': 'Join the game',
  'Подбираем соперников': 'Finding opponents',
  'Игра начнётся через пару секунд': 'The game will start in a few seconds',
  'в игре': 'in game',
  'Игровая комната': 'Game room',
  'Поделись кодом': 'Share the code',
  'Позвать друзей ↗': 'Invite friends ↗',
  'Заходи ко мне в': 'Come play with me in',
  'Код комнаты': 'Room code',
  'ХОЗЯИН': 'HOST',
  'БОТ': 'BOT',
  'готов': 'ready',
  'Ждём игроков…': 'Waiting for players…',
  'Пустые места займут боты, когда начнёшь.': 'Empty seats will be filled by bots when you start.',
  'Раскладываем…': 'Setting up…',
  'Начать игру 🎲': 'Start the game 🎲',
  'Ждём, пока хозяин начнёт…': 'Waiting for the host to start…',

  // -- Rules.tsx ------------------------------------------------------------
  'Бросай и ходи': 'Roll and move',
  'В свой ход бросай два кубика и двигайся по кругу. Выпал дубль, ходишь ещё раз.': 'On your turn, roll two dice and move around the board. Roll doubles and you go again.',
  'Скупай недвижимость': 'Buy up property',
  'Встал на свободную улицу, вокзал или предприятие, можешь купить. Прошёл «Старт», получаешь 2000.': 'Land on a free street, station, or utility and you can buy it. Pass Start to collect 2000.',
  'Собирай аренду': 'Collect rent',
  'Соперники, попавшие на твою клетку, платят тебе. Чем дороже участок, тем больше доход.': 'Rivals who land on your space pay you. The pricier the plot, the bigger the income.',
  'Монополии и дома': 'Monopolies and houses',
  'Собрал всю цветную группу, аренда удваивается. На полной группе строй дома и отель, доход растёт в разы.': 'Own a whole colour group and rent doubles. On a full group, build houses and a hotel to multiply your income.',
  'Шанс и Казна': 'Chance and Treasury',
  'Особые клетки дают карту события: деньги, переезд или дорога прямиком на нары.': 'Special spaces draw an event card: money, a move, or a one-way trip to jail.',
  'Три дубля подряд или клетка «На нары» сажают в тюрьму. Выходишь по залогу, по карте или выбросив дубль.': 'Three doubles in a row or the Go to Jail space lands you in jail. Get out by paying, using a card, or rolling doubles.',
  'Победа': 'Winning',
  'Не хватило денег, банк продаёт твои дома и закладывает участки. Совсем нечем платить, ты выбываешь. Последний магнат за столом побеждает.': 'If you run short, the bank sells your houses and mortgages your plots. If you still cannot pay, you are out. The last magnate at the table wins.',
  'Магнат это уютная настолка про недвижимость в духе «Монополии». Скупай улицы, собирай цветные группы в': 'Magnate is a cosy real-estate board game in the spirit of Monopoly. Buy up streets, gather colour groups into',
  'монополии': 'monopolies',
  'и застраивай их домами, чтобы соперники платили тебе по-крупному.': 'and build them up with houses so your rivals pay you big.',
  'Сыграть одиночную партию 🎲': 'Play a single-player game 🎲',

  // -- Leaderboard.tsx ------------------------------------------------------
  'Рейтинг 🏆': 'Leaderboard 🏆',
  'Партий': 'Games',
  'Лучшая серия': 'Best streak',
  'Таблица пока пуста': 'The board is still empty',
  'Сыграй партию и стань первым магнатом в рейтинге!': 'Play a game and become the first magnate on the board!',
  'Сыграть 🎲': 'Play 🎲',
  ' побед': ' wins',
}
